# Generated by Django 5.2.11 on 2026-02-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActionHistory',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('admin_id', models.UUIDField()),
                ('admin_name', models.TextField(blank=True, null=True)),
                ('action', models.TextField()),
                ('target_user_id', models.UUIDField(blank=True, null=True)),
                ('target_user_name', models.TextField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'admin_action_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdminSettings',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('category', models.TextField()),
                ('key', models.TextField()),
                ('value', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('description', models.TextField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'admin_settings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(unique=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('first_name', models.TextField(blank=True, null=True)),
                ('last_name', models.TextField(blank=True, null=True)),
                ('gender', models.TextField(blank=True, null=True)),
                ('language', models.TextField(blank=True, null=True)),
                ('avatar_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'profiles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('role', models.TextField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'user_roles',
                'managed': False,
            },
        ),
    ]
