# Generated by Django 5.2.11 on 2026-02-21 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_apps', '0002_otprecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminactionhistory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='adminsettings',
            options={},
        ),
        migrations.AlterModelOptions(
            name='profiles',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userroles',
            options={},
        ),
    ]
