# Generated by Django 5.2.11 on 2026-02-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_apps', '0006_profiles_bank_transfer_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='is_blocked',
            field=models.BooleanField(default=False, help_text='Заблокирован ли аккаунт'),
        ),
        migrations.AddField(
            model_name='profiles',
            name='is_vip',
            field=models.BooleanField(default=False, help_text='VIP статус'),
        ),
        migrations.AddField(
            model_name='profiles',
            name='referral_level',
            field=models.CharField(choices=[('R1(DEFAULT)', 'R1 (Default)'), ('R2', 'R2'), ('R3', 'R3'), ('R4', 'R4'), ('Partner', 'Partner')], default='R1(DEFAULT)', max_length=50),
        ),
        migrations.AddField(
            model_name='profiles',
            name='subscription_type',
            field=models.CharField(choices=[('default', 'Бесплатная (Дефолт)'), ('standard', 'Стандартная'), ('premium', 'Премиум'), ('vip', 'VIP')], default='default', max_length=50),
        ),
    ]
