# Generated by Django 5.2.11 on 2026-03-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_apps', '0008_profiles_usdt_limits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='referral_level',
            field=models.CharField(choices=[('r1', 'R1 (Default)'), ('r2', 'R2'), ('r3', 'R3'), ('r4', 'R4'), ('partner', 'Partner')], default='R1(DEFAULT)', max_length=50),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='subscription_type',
            field=models.CharField(choices=[('smart', 'Smart'), ('agent', 'Agent'), ('pro', 'PRO'), ('vip', 'VIP'), ('partner', 'Партнер')], default='default', max_length=50),
        ),
    ]
