# Generated by Django 5.2.11 on 2026-03-03 19:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_apps', '0010_profiles_top_up_limits'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotificationSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('telegram_chat_id', models.CharField(blank=True, help_text='ID чата в Telegram', max_length=100, null=True)),
                ('telegram_enabled', models.BooleanField(default=False)),
                ('whatsapp_number', models.CharField(blank=True, help_text='Номер в формате 996555123456', max_length=50, null=True)),
                ('whatsapp_enabled', models.BooleanField(default=False)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройка уведомлений админа',
                'verbose_name_plural': 'Настройки уведомлений админов',
                'db_table': 'admin_notification_settings',
            },
        ),
    ]
