# Generated by Django 5.2.11 on 2026-03-04 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_apps', '0011_adminnotificationsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminnotificationsettings',
            name='telegram_username',
            field=models.CharField(blank=True, help_text='Username (например, @username)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='adminnotificationsettings',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
