# Generated by Django 5.2.11 on 2026-03-06 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_apps', '0012_adminnotificationsettings_telegram_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WahaSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(default='default', max_length=255, verbose_name='Имя сессии WAHA')),
                ('api_url', models.CharField(default='http://localhost:3000', max_length=255, verbose_name='URL API (с портом)')),
                ('api_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='API Key (если есть)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'WAHA Сессия',
                'verbose_name_plural': 'WAHA Сессии',
            },
        ),
    ]
