# Generated by Django 5.2.11 on 2026-03-08 10:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_apps', '0013_wahasession'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotificationSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('telegram_username', models.CharField(blank=True, help_text='Username (например, @username)', max_length=100, null=True)),
                ('telegram_chat_id', models.CharField(blank=True, max_length=100, null=True)),
                ('telegram_enabled', models.BooleanField(default=False)),
                ('whatsapp_number', models.CharField(blank=True, help_text='Номер в формате 996555123456', max_length=50, null=True)),
                ('whatsapp_enabled', models.BooleanField(default=False)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройка уведомлений пользователя',
                'verbose_name_plural': 'Настройки уведомлений пользователей',
                'db_table': 'user_notification_settings',
            },
        ),
        migrations.AddField(
            model_name='profiles',
            name='verification_status',
            field=models.CharField(choices=[('unverified', 'Не верифицирован'), ('pending', 'В ожидании'), ('verified', 'Верифицирован'), ('rejected', 'Отклонен')], default='unverified', help_text='Статус верификации', max_length=20),
        ),
    ]
