# Generated by Django 5.2.11 on 2026-03-10 19:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_apps', '0014_usernotificationsettings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiChatHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=50)),
                ('platform', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_chat_history',
                'ordering': ['created_at'],
            },
        ),
    ]
