"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from decouple import config
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
from datetime import timedelta
from corsheaders.defaults import default_headers

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG')

ALLOWED_HOSTS = ['*']

CORS_ORIGIN_ALLOW_ALL = True 
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = default_headers + (
    "cache-control",
    "Access-Control-Allow-Headers",
    "Access-Control-Allow-Credentials",
)

CSRF_TRUSTED_ORIGINS = ['https://ueasycard.com', 'https://www.ueasycard.com', 'https://dced9e95-c6f0-4f31-ac4c-9e0c31ea7407.lovableproject.com']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #APPS
    'apps.accounts_apps',
    'apps.cards_apps',
    'apps.transactions_apps',
    #API
    'api.accounts_api',
    'api.cards_api',
    'api.transactions_api',
    #INSTALLED
    'channels',
    'django_filters',
    'corsheaders',
    'djoser',
    'drf_yasg',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework.authtoken',
    'simple_history',
    'core'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

ROOT_URLCONF = 'core.urls'

TELEGRAM_BOT_TOKEN = config('TELEGRAM_BOT_TOKEN', default='')
WAHA_API_URL = config('WAHA_API_URL', default='http://localhost:3000')
WAHA_SESSION_NAME = config('WAHA_SESSION_NAME', default='default')
WHATSAPP_API_KEY = config('WHATSAPP_API_KEY', default='5f0ed637143a4fddac67e3108cfd80ed')

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default=EMAIL_HOST_USER)

TRANSACTION_EMAIL_HOST = config('TRANSACTION_EMAIL_HOST', default=EMAIL_HOST)
TRANSACTION_EMAIL_PORT = config('TRANSACTION_EMAIL_PORT', default=EMAIL_PORT, cast=int)
TRANSACTION_EMAIL_USE_TLS = config('TRANSACTION_EMAIL_USE_TLS', default=EMAIL_USE_TLS, cast=bool)
TRANSACTION_EMAIL_HOST_USER = config('TRANSACTION_EMAIL_HOST_USER', default=EMAIL_HOST_USER)
TRANSACTION_EMAIL_HOST_PASSWORD = config('TRANSACTION_EMAIL_HOST_PASSWORD', default=EMAIL_HOST_PASSWORD)

AI_SERVICE_TOKEN = config('AI_SERVICE_TOKEN', default='SuperSecretAiBotToken_2026_EasyCard_XYZD_DFMC_GH4J_45JFO_3468_DJO')

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=7),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'AUTH_HEADER_TYPES': ('JWT',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'api.accounts_api.authentication.ApofizTokenAuthentication',
    ),
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
    ),
    'DEFAULT_PAGINATION_CLASS': 
      'rest_framework.pagination.LimitOffsetPagination',
      'PAGE_SIZE': 10,
    'COERCE_DECIMAL_TO_STRING': False,
}

DJOSER = {
    'USERNAME_RESET_CONFIRM_URL': '#/username/reset/confirm/{uid}/{token}',
    'SEND_ACTIVATION_EMAIL': False,
    'USER_CREATE_PASSWORD_RETYPE': False,
    'ACTIVATION_URL': "api/auth/user/activate/{uid}/{token}/",
    'PASSWORD_RESET_CONFIRM_URL': 'api/auth/password/reset/confirm/{uid}/{token}',

}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

# --- XERIME API CONFIG ---
XERIME_API_URL = config('XERIME_API_URL', default='https://api.xerime.com/xerimeAPI/api/v2')
XERIME_USERNAME = config('XERIME_USERNAME', default='your_username')
XERIME_PASSWORD = config('XERIME_PASSWORD', default='your_password')


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT'),
    }
}

USER_TELEGRAM_BOT_TOKEN = config('USER_TELEGRAM_BOT_TOKEN', default='8673662030:AAF-oElXbfGC7YYVJvCLDrLWiAznhj_0nqw')
USER_TELEGRAM_BOT_USERNAME = config('USER_TELEGRAM_BOT_USERNAME', default='@uEasyCard_Bot')


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Asia/Almaty'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR, 'static-root')
STATIC_URL = 'static-root/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
