# Generated by Django 5.2.11 on 2026-02-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('type', models.TextField()),
                ('name', models.TextField()),
                ('status', models.TextField()),
                ('balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('last_four_digits', models.CharField(blank=True, max_length=4, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('card_number_encrypted', models.TextField(blank=True, null=True)),
                ('cvv_encrypted', models.TextField(blank=True, null=True)),
                ('annual_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'cards',
                'managed': False,
            },
        ),
    ]
