# Generated by Django 5.2.11 on 2026-02-21 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards_apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cards',
            options={},
        ),
    ]
