# Generated by Django 5.2.11 on 2026-02-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('type', models.TextField()),
                ('status', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(max_length=3)),
                ('fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('original_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('original_currency', models.CharField(blank=True, max_length=3, null=True)),
                ('merchant_name', models.TextField(blank=True, null=True)),
                ('merchant_category', models.TextField(blank=True, null=True)),
                ('recipient_card', models.CharField(blank=True, max_length=19, null=True)),
                ('sender_name', models.TextField(blank=True, null=True)),
                ('sender_card', models.CharField(blank=True, max_length=19, null=True)),
                ('reference_id', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'transactions',
                'managed': False,
            },
        ),
    ]
