# Generated by Django 5.2.11 on 2026-02-19 17:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions_apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDepositAccounts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('iban', models.CharField(max_length=34, unique=True)),
                ('bank_name', models.CharField(max_length=255)),
                ('beneficiary', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'bank_deposit_accounts',
            },
        ),
        migrations.CreateModel(
            name='BankInboundPayments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(max_length=3)),
                ('sender', models.CharField(max_length=255)),
                ('iban', models.CharField(max_length=34)),
                ('reference', models.CharField(max_length=255)),
                ('provider_id', models.CharField(max_length=255, unique=True)),
                ('matched', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bank_inbound_payments',
            },
        ),
        migrations.CreateModel(
            name='CryptoInboundTransactions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tx_hash', models.CharField(max_length=255, unique=True)),
                ('network', models.CharField(max_length=50)),
                ('token', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=20)),
                ('from_address', models.CharField(max_length=255)),
                ('to_address', models.CharField(max_length=255)),
                ('confirmations', models.IntegerField(default=0)),
                ('received_at', models.DateTimeField()),
                ('raw_payload', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'crypto_inbound_transactions',
            },
        ),
        migrations.CreateModel(
            name='BalanceMovements',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('account_type', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('type', models.CharField(choices=[('debit', 'Debit (-)'), ('credit', 'Credit (+)')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='transactions_apps.transactions')),
            ],
            options={
                'db_table': 'balance_movements',
            },
        ),
        migrations.CreateModel(
            name='BankWithdrawals',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('beneficiary_iban', models.CharField(max_length=34)),
                ('iban_validated', models.BooleanField(default=False)),
                ('beneficiary_name', models.CharField(max_length=255)),
                ('beneficiary_bank_name', models.CharField(max_length=255)),
                ('from_card_id', models.UUIDField()),
                ('amount_aed', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fee_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_debit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('provider_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_reason', models.TextField(blank=True, null=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_withdrawal', to='transactions_apps.transactions')),
            ],
            options={
                'db_table': 'bank_withdrawals',
            },
        ),
        migrations.CreateModel(
            name='CardTransfers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_user_id', models.UUIDField()),
                ('receiver_user_id', models.UUIDField()),
                ('sender_card_id', models.UUIDField()),
                ('receiver_card_id', models.UUIDField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fee_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card_transfer', to='transactions_apps.transactions')),
            ],
            options={
                'db_table': 'card_transfers',
            },
        ),
        migrations.CreateModel(
            name='CryptoWithdrawals',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('token', models.CharField(max_length=20)),
                ('network', models.CharField(max_length=20)),
                ('to_address', models.CharField(max_length=255)),
                ('address_validated', models.BooleanField(default=False)),
                ('amount_crypto', models.DecimalField(decimal_places=6, max_digits=15)),
                ('fee_amount', models.DecimalField(decimal_places=6, max_digits=15)),
                ('fee_type', models.CharField(max_length=50)),
                ('total_debit', models.DecimalField(decimal_places=6, max_digits=15)),
                ('provider', models.CharField(blank=True, max_length=100, null=True)),
                ('provider_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('tx_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('confirmations', models.IntegerField(default=0)),
                ('failed_reason', models.TextField(blank=True, null=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_withdrawal', to='transactions_apps.transactions')),
            ],
            options={
                'db_table': 'crypto_withdrawals',
            },
        ),
        migrations.CreateModel(
            name='TopupsBank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('channel', models.CharField(default='bank_wire', max_length=50)),
                ('transfer_rail', models.CharField(choices=[('UAE_LOCAL_AED', 'UAE Local AED'), ('SWIFT_INTL', 'SWIFT International')], max_length=50)),
                ('reference_value', models.CharField(max_length=100)),
                ('fee_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('min_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('instructions_snapshot', models.JSONField()),
                ('sender_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sender_bank', models.CharField(blank=True, max_length=255, null=True)),
                ('sender_iban', models.CharField(blank=True, max_length=34, null=True)),
                ('credited_card_id', models.UUIDField(blank=True, null=True)),
                ('deposit_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions_apps.bankdepositaccounts')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_topup', to='transactions_apps.transactions')),
            ],
            options={
                'db_table': 'topups_bank',
            },
        ),
        migrations.CreateModel(
            name='TopupsCrypto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('card_id', models.UUIDField()),
                ('token', models.CharField(max_length=20)),
                ('network', models.CharField(max_length=20)),
                ('deposit_address', models.CharField(max_length=255)),
                ('address_provider', models.CharField(max_length=100)),
                ('qr_payload', models.TextField()),
                ('min_amount', models.DecimalField(decimal_places=6, max_digits=15)),
                ('fee_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('rate_snapshot', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
                ('tx_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('from_address', models.CharField(blank=True, max_length=255, null=True)),
                ('amount_crypto', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('fee_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('credited_amount_aed', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_topup', to='transactions_apps.transactions')),
            ],
            options={
                'db_table': 'topups_crypto',
            },
        ),
    ]
