# Generated by Django 5.2.11 on 2026-02-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions_apps', '0002_bankdepositaccounts_bankinboundpayments_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactions',
            options={},
        ),
        migrations.AlterField(
            model_name='balancemovements',
            name='user_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bankwithdrawals',
            name='user_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cardtransfers',
            name='receiver_user_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cardtransfers',
            name='sender_user_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cryptowithdrawals',
            name='user_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='topupsbank',
            name='user_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='topupscrypto',
            name='user_id',
            field=models.CharField(max_length=50),
        ),
    ]
