# Generated by Django 5.2.11 on 2026-02-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions_apps', '0005_alter_bankwithdrawals_from_card_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='receiver_id',
            field=models.CharField(blank=True, help_text="ID получателя или 'EXTERNAL'", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='sender_id',
            field=models.CharField(blank=True, help_text="ID отправителя или 'EXTERNAL'", max_length=50, null=True),
        ),
    ]
