# Generated by Django 5.2.11 on 2026-02-23 17:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions_apps', '0006_transactions_receiver_id_transactions_sender_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeRevenue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=50)),
                ('fee_type', models.CharField(max_length=30)),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fee_currency', models.CharField(default='AED', max_length=3)),
                ('fee_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('base_currency', models.CharField(max_length=3)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('card_id', models.UUIDField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_revenues', to='transactions_apps.transactions')),
            ],
            options={
                'db_table': 'fee_revenue',
                'indexes': [models.Index(fields=['fee_type', 'created_at'], name='fee_revenue_fee_typ_3a26ac_idx'), models.Index(fields=['user_id'], name='fee_revenue_user_id_22a739_idx'), models.Index(fields=['created_at'], name='fee_revenue_created_adc481_idx')],
            },
        ),
    ]
