# Generated by Django 5.2.11 on 2026-02-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions_apps', '0007_feerevenue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankinboundpayments',
            name='currency',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='feerevenue',
            name='base_currency',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='feerevenue',
            name='fee_currency',
            field=models.CharField(default='AED', max_length=10),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='currency',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='original_currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
