# Generated by Django 5.2.11 on 2026-02-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions_apps', '0008_alter_bankinboundpayments_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='receiver_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
