# Generated by Django 5.2.11 on 2026-03-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions_apps', '0009_transactions_receiver_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topupscrypto',
            name='card_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
