# Generated by Django 5.2.11 on 2026-04-02 18:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions_apps', '0010_alter_topupscrypto_card_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedFiatRecipients',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('iban', models.CharField(max_length=34)),
                ('beneficiary_name', models.CharField(max_length=255)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'saved_fiat_recipients',
                'ordering': ['-created_at'],
                'unique_together': {('user_id', 'iban')},
            },
        ),
    ]
