import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

function formatDate(dateStr: string): string {
  const date = new Date(dateStr);
  return `${date.getDate().toString().padStart(2, '0')}.${(date.getMonth() + 1).toString().padStart(2, '0')}.${date.getFullYear()}`;
}

function formatTime(dateStr: string): string {
  const date = new Date(dateStr);
  return `${date.getHours().toString().padStart(2, '0')}:${date.getMinutes().toString().padStart(2, '0')}`;
}

function esc(val: string): string {
  if (!val) return '';
  return val.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

// ─── i18n translations ───
type Lang = 'ru' | 'en' | 'de' | 'tr' | 'zh' | 'ar' | 'es';

const i18n: Record<Lang, Record<string, string>> = {
  ru: {
    reportTitle: 'Отчёт по транзакциям', generatedOn: 'Дата формирования', autoGenerated: 'Документ сформирован автоматически',
    totalOps: 'Всего операций', income: 'Приход', expense: 'Расход', balance: 'Баланс',
    detailTitle: 'Детализация операций', num: '№', date: 'Дата', type: 'Тип', description: 'Описание',
    amount: 'Сумма', status: 'Статус', sender: 'Отправитель', receiver: 'Получатель', fee: 'Комиссия',
    allTx: 'Все транзакции', from: 'с', to: 'по', wallet: 'Кошелёк', account: 'Счёт', card: 'Карта',
    notAuthorized: 'Не авторизован', fetchError: 'Не удалось получить транзакции', genError: 'Ошибка при формировании отчёта',
    pending: 'В обработке', processing: 'Обрабатывается', settled: 'Завершено', completed: 'Завершено',
    failed: 'Ошибка', cancelled: 'Отменено', declined: 'Отклонено',
    top_up: 'Пополнение', withdrawal: 'Вывод', transfer_in: 'Входящий перевод', transfer_out: 'Исходящий перевод',
    card_payment: 'Оплата картой', refund: 'Возврат', fee_type: 'Комиссия', cashback: 'Кэшбэк',
    card_activation: 'Активация карты', card_transfer: 'Перевод между картами', bank_transfer: 'Банковский перевод',
    bank_transfer_incoming: 'Входящий банк. перевод', crypto_withdrawal: 'Вывод крипто', crypto_send: 'Отправка крипто',
    crypto_deposit: 'Пополнение крипто', crypto_to_card: 'Крипто → Карта', crypto_to_iban: 'Крипто → IBAN',
    crypto_to_crypto: 'Крипто → Крипто', bank_to_crypto: 'Банк → Крипто', iban_to_iban: 'IBAN → IBAN',
    internal_transfer: 'Внутренний перевод', payment: 'Платёж',
  },
  en: {
    reportTitle: 'Transaction Report', generatedOn: 'Generated on', autoGenerated: 'Document generated automatically',
    totalOps: 'Total operations', income: 'Income', expense: 'Expense', balance: 'Balance',
    detailTitle: 'Transaction Details', num: '#', date: 'Date', type: 'Type', description: 'Description',
    amount: 'Amount', status: 'Status', sender: 'Sender', receiver: 'Receiver', fee: 'Fee',
    allTx: 'All transactions', from: 'from', to: 'to', wallet: 'Wallet', account: 'Account', card: 'Card',
    notAuthorized: 'Not authorized', fetchError: 'Failed to fetch transactions', genError: 'Report generation error',
    pending: 'Pending', processing: 'Processing', settled: 'Settled', completed: 'Completed',
    failed: 'Failed', cancelled: 'Cancelled', declined: 'Declined',
    top_up: 'Top Up', withdrawal: 'Withdrawal', transfer_in: 'Incoming Transfer', transfer_out: 'Outgoing Transfer',
    card_payment: 'Card Payment', refund: 'Refund', fee_type: 'Fee', cashback: 'Cashback',
    card_activation: 'Card Activation', card_transfer: 'Card Transfer', bank_transfer: 'Bank Transfer',
    bank_transfer_incoming: 'Incoming Bank Transfer', crypto_withdrawal: 'Crypto Withdrawal', crypto_send: 'Crypto Send',
    crypto_deposit: 'Crypto Deposit', crypto_to_card: 'Crypto → Card', crypto_to_iban: 'Crypto → IBAN',
    crypto_to_crypto: 'Crypto → Crypto', bank_to_crypto: 'Bank → Crypto', iban_to_iban: 'IBAN → IBAN',
    internal_transfer: 'Internal Transfer', payment: 'Payment',
  },
  de: {
    reportTitle: 'Transaktionsbericht', generatedOn: 'Erstellt am', autoGenerated: 'Dokument automatisch erstellt',
    totalOps: 'Gesamtoperationen', income: 'Einnahmen', expense: 'Ausgaben', balance: 'Saldo',
    detailTitle: 'Transaktionsdetails', num: 'Nr.', date: 'Datum', type: 'Typ', description: 'Beschreibung',
    amount: 'Betrag', status: 'Status', sender: 'Absender', receiver: 'Empfänger', fee: 'Gebühr',
    allTx: 'Alle Transaktionen', from: 'von', to: 'bis', wallet: 'Wallet', account: 'Konto', card: 'Karte',
    notAuthorized: 'Nicht autorisiert', fetchError: 'Transaktionen konnten nicht abgerufen werden', genError: 'Fehler bei der Berichterstellung',
    pending: 'Ausstehend', processing: 'In Bearbeitung', settled: 'Abgeschlossen', completed: 'Abgeschlossen',
    failed: 'Fehlgeschlagen', cancelled: 'Storniert', declined: 'Abgelehnt',
    top_up: 'Aufladung', withdrawal: 'Auszahlung', transfer_in: 'Eingehende Überweisung', transfer_out: 'Ausgehende Überweisung',
    card_payment: 'Kartenzahlung', refund: 'Rückerstattung', fee_type: 'Gebühr', cashback: 'Cashback',
    card_activation: 'Kartenaktivierung', card_transfer: 'Kartenüberweisung', bank_transfer: 'Banküberweisung',
    bank_transfer_incoming: 'Eingehende Banküberweisung', crypto_withdrawal: 'Krypto-Auszahlung', crypto_send: 'Krypto-Versand',
    crypto_deposit: 'Krypto-Einzahlung', crypto_to_card: 'Krypto → Karte', crypto_to_iban: 'Krypto → IBAN',
    crypto_to_crypto: 'Krypto → Krypto', bank_to_crypto: 'Bank → Krypto', iban_to_iban: 'IBAN → IBAN',
    internal_transfer: 'Interne Überweisung', payment: 'Zahlung',
  },
  tr: {
    reportTitle: 'İşlem Raporu', generatedOn: 'Oluşturulma tarihi', autoGenerated: 'Belge otomatik olarak oluşturuldu',
    totalOps: 'Toplam işlem', income: 'Gelir', expense: 'Gider', balance: 'Bakiye',
    detailTitle: 'İşlem Detayları', num: 'No', date: 'Tarih', type: 'Tür', description: 'Açıklama',
    amount: 'Tutar', status: 'Durum', sender: 'Gönderen', receiver: 'Alıcı', fee: 'Komisyon',
    allTx: 'Tüm işlemler', from: 'den', to: 'e', wallet: 'Cüzdan', account: 'Hesap', card: 'Kart',
    notAuthorized: 'Yetkisiz', fetchError: 'İşlemler alınamadı', genError: 'Rapor oluşturma hatası',
    pending: 'Beklemede', processing: 'İşleniyor', settled: 'Tamamlandı', completed: 'Tamamlandı',
    failed: 'Başarısız', cancelled: 'İptal edildi', declined: 'Reddedildi',
    top_up: 'Yükleme', withdrawal: 'Çekim', transfer_in: 'Gelen Transfer', transfer_out: 'Giden Transfer',
    card_payment: 'Kart Ödeme', refund: 'İade', fee_type: 'Komisyon', cashback: 'Cashback',
    card_activation: 'Kart Aktivasyonu', card_transfer: 'Kartlar Arası Transfer', bank_transfer: 'Banka Transferi',
    bank_transfer_incoming: 'Gelen Banka Transferi', crypto_withdrawal: 'Kripto Çekim', crypto_send: 'Kripto Gönderim',
    crypto_deposit: 'Kripto Yükleme', crypto_to_card: 'Kripto → Kart', crypto_to_iban: 'Kripto → IBAN',
    crypto_to_crypto: 'Kripto → Kripto', bank_to_crypto: 'Banka → Kripto', iban_to_iban: 'IBAN → IBAN',
    internal_transfer: 'Dahili Transfer', payment: 'Ödeme',
  },
  zh: {
    reportTitle: '交易报告', generatedOn: '生成日期', autoGenerated: '文件自动生成',
    totalOps: '总操作数', income: '收入', expense: '支出', balance: '余额',
    detailTitle: '交易明细', num: '序号', date: '日期', type: '类型', description: '描述',
    amount: '金额', status: '状态', sender: '发送方', receiver: '接收方', fee: '手续费',
    allTx: '所有交易', from: '从', to: '至', wallet: '钱包', account: '账户', card: '卡',
    notAuthorized: '未授权', fetchError: '无法获取交易', genError: '报告生成错误',
    pending: '待处理', processing: '处理中', settled: '已完成', completed: '已完成',
    failed: '失败', cancelled: '已取消', declined: '已拒绝',
    top_up: '充值', withdrawal: '提现', transfer_in: '转入', transfer_out: '转出',
    card_payment: '卡支付', refund: '退款', fee_type: '手续费', cashback: '返现',
    card_activation: '卡激活', card_transfer: '卡间转账', bank_transfer: '银行转账',
    bank_transfer_incoming: '银行转入', crypto_withdrawal: '加密提现', crypto_send: '加密发送',
    crypto_deposit: '加密充值', crypto_to_card: '加密 → 卡', crypto_to_iban: '加密 → IBAN',
    crypto_to_crypto: '加密 → 加密', bank_to_crypto: '银行 → 加密', iban_to_iban: 'IBAN → IBAN',
    internal_transfer: '内部转账', payment: '支付',
  },
  ar: {
    reportTitle: 'تقرير المعاملات', generatedOn: 'تاريخ الإنشاء', autoGenerated: 'تم إنشاء المستند تلقائياً',
    totalOps: 'إجمالي العمليات', income: 'الدخل', expense: 'المصروفات', balance: 'الرصيد',
    detailTitle: 'تفاصيل المعاملات', num: 'رقم', date: 'التاريخ', type: 'النوع', description: 'الوصف',
    amount: 'المبلغ', status: 'الحالة', sender: 'المرسل', receiver: 'المستلم', fee: 'العمولة',
    allTx: 'جميع المعاملات', from: 'من', to: 'إلى', wallet: 'محفظة', account: 'حساب', card: 'بطاقة',
    notAuthorized: 'غير مصرح', fetchError: 'تعذر جلب المعاملات', genError: 'خطأ في إنشاء التقرير',
    pending: 'قيد الانتظار', processing: 'جاري المعالجة', settled: 'مكتمل', completed: 'مكتمل',
    failed: 'فشل', cancelled: 'ملغى', declined: 'مرفوض',
    top_up: 'إيداع', withdrawal: 'سحب', transfer_in: 'تحويل وارد', transfer_out: 'تحويل صادر',
    card_payment: 'دفع بالبطاقة', refund: 'استرداد', fee_type: 'عمولة', cashback: 'استرداد نقدي',
    card_activation: 'تفعيل البطاقة', card_transfer: 'تحويل بين البطاقات', bank_transfer: 'تحويل بنكي',
    bank_transfer_incoming: 'تحويل بنكي وارد', crypto_withdrawal: 'سحب كريبتو', crypto_send: 'إرسال كريبتو',
    crypto_deposit: 'إيداع كريبتو', crypto_to_card: 'كريبتو → بطاقة', crypto_to_iban: 'كريبتو → IBAN',
    crypto_to_crypto: 'كريبتو → كريبتو', bank_to_crypto: 'بنك → كريبتو', iban_to_iban: 'IBAN → IBAN',
    internal_transfer: 'تحويل داخلي', payment: 'دفعة',
  },
  es: {
    reportTitle: 'Informe de Transacciones', generatedOn: 'Fecha de generación', autoGenerated: 'Documento generado automáticamente',
    totalOps: 'Total operaciones', income: 'Ingresos', expense: 'Gastos', balance: 'Saldo',
    detailTitle: 'Detalle de Operaciones', num: 'Nº', date: 'Fecha', type: 'Tipo', description: 'Descripción',
    amount: 'Monto', status: 'Estado', sender: 'Remitente', receiver: 'Destinatario', fee: 'Comisión',
    allTx: 'Todas las transacciones', from: 'desde', to: 'hasta', wallet: 'Billetera', account: 'Cuenta', card: 'Tarjeta',
    notAuthorized: 'No autorizado', fetchError: 'No se pudieron obtener las transacciones', genError: 'Error al generar el informe',
    pending: 'Pendiente', processing: 'Procesando', settled: 'Completado', completed: 'Completado',
    failed: 'Fallido', cancelled: 'Cancelado', declined: 'Rechazado',
    top_up: 'Recarga', withdrawal: 'Retiro', transfer_in: 'Transferencia entrante', transfer_out: 'Transferencia saliente',
    card_payment: 'Pago con tarjeta', refund: 'Reembolso', fee_type: 'Comisión', cashback: 'Cashback',
    card_activation: 'Activación de tarjeta', card_transfer: 'Transferencia entre tarjetas', bank_transfer: 'Transferencia bancaria',
    bank_transfer_incoming: 'Transf. bancaria entrante', crypto_withdrawal: 'Retiro cripto', crypto_send: 'Envío cripto',
    crypto_deposit: 'Depósito cripto', crypto_to_card: 'Cripto → Tarjeta', crypto_to_iban: 'Cripto → IBAN',
    crypto_to_crypto: 'Cripto → Cripto', bank_to_crypto: 'Banco → Cripto', iban_to_iban: 'IBAN → IBAN',
    internal_transfer: 'Transferencia interna', payment: 'Pago',
  },
};

function t(lang: Lang, key: string): string {
  return i18n[lang]?.[key] || i18n['en'][key] || key;
}

function getStatusLabel(status: string, lang: Lang): { label: string; color: string } {
  const colorMap: Record<string, string> = {
    pending: '#f59e0b', processing: '#3b82f6', settled: '#10b981', completed: '#10b981',
    failed: '#ef4444', cancelled: '#6b7280', declined: '#ef4444',
  };
  return { label: t(lang, status) || status, color: colorMap[status] || '#6b7280' };
}

function getTypeLabel(type: string, lang: Lang): string {
  return t(lang, type) || type;
}

function getLocale(lang: Lang): string {
  const localeMap: Record<Lang, string> = { ru: 'ru-RU', en: 'en-US', de: 'de-DE', tr: 'tr-TR', zh: 'zh-CN', ar: 'ar-AE', es: 'es-ES' };
  return localeMap[lang] || 'en-US';
}

interface AssetBalance {
  label: string;
  amount: string;
  currency: string;
}

function buildHTML(filtered: any[], periodLabel: string, userName: string, generatedDate: string, totalIn: number, totalOut: number, assetBalances: AssetBalance[] = [], lang: Lang = 'ru'): string {
  const locale = getLocale(lang);
  const txRows = filtered.map((tx: any, idx: number) => {
    const date = tx.created_at ? formatDate(tx.created_at) : '';
    const time = tx.created_at ? formatTime(tx.created_at) : '';
    const type = getTypeLabel(tx.type, lang);

    let description = '';
    if (tx.display?.title) {
      description = tx.display.title;
      if (tx.display.subtitle) description += `<br><span class="sub">${esc(tx.display.subtitle)}</span>`;
    } else if (tx.merchant_name) {
      description = tx.merchant_name;
    } else if (tx.description) {
      description = tx.description;
    }

    let amount = '';
    let sign = '';
    if (tx.display?.primary_amount) {
      const pa = tx.display.primary_amount;
      sign = pa.sign || '';
      amount = `${sign}${pa.amount}`;
    } else if (tx.amount !== undefined) {
      amount = String(tx.amount);
      sign = parseFloat(tx.amount) >= 0 ? '+' : '-';
    }
    const currency = tx.display?.primary_amount?.currency || tx.currency || 'AED';
    const amountClass = sign === '+' ? 'amount-in' : sign === '-' ? 'amount-out' : '';

    const st = getStatusLabel(tx.status, lang);
    const senderName = esc(tx.sender_name || tx.metadata?.sender_name || '—');
    const receiverName = esc(tx.receiver_name || tx.metadata?.beneficiary_name || tx.metadata?.receiver_name || '—');
    
    // Build masked account details for sender
    const senderDetails: string[] = [];
    if (tx.sender_card_mask) senderDetails.push(`•••• ${tx.sender_card_mask.slice(-4)}`);
    // IBAN
    const sIban = tx.metadata?.sender_iban_mask || tx.metadata?.sender_iban || tx.metadata?.from_iban;
    if (sIban) {
      const s = String(sIban);
      senderDetails.push(s.length > 8 ? `${s.slice(0, 4)}••••${s.slice(-4)}` : s);
    }
    // Crypto address
    const sAddr = tx.metadata?.from_address || tx.metadata?.from_wallet_address || tx.metadata?.crypto_address || tx.metadata?.sender_crypto_address;
    if (sAddr) {
      const a = String(sAddr);
      senderDetails.push(`${a.slice(0, 6)}••••${a.slice(-4)}`);
    }
    // Card number from metadata
    if (tx.metadata?.from_card_number || tx.metadata?.sender_card_number) {
      const c = String(tx.metadata?.from_card_number || tx.metadata?.sender_card_number);
      senderDetails.push(`•••• ${c.slice(-4)}`);
    }
    // Movements fallback (index 0 = sender)
    if (senderDetails.length === 0 && tx.movements && Array.isArray(tx.movements) && tx.movements[0]) {
      const m = tx.movements[0];
      if (m.card_mask) senderDetails.push(`•••• ${m.card_mask.slice(-4)}`);
      else if (m.iban) { const i = String(m.iban); senderDetails.push(`${i.slice(0, 4)}••••${i.slice(-4)}`); }
      else if (m.address) { const a = String(m.address); senderDetails.push(`${a.slice(0, 6)}••••${a.slice(-4)}`); }
    }
    
    // Build masked account details for receiver
    const receiverDetails: string[] = [];
    if (tx.receiver_card_mask) receiverDetails.push(`•••• ${tx.receiver_card_mask.slice(-4)}`);
    // IBAN
    const rIban = tx.metadata?.receiver_iban_mask || tx.metadata?.beneficiary_iban || tx.metadata?.receiver_iban || tx.metadata?.to_iban;
    if (rIban) {
      const s = String(rIban);
      receiverDetails.push(s.length > 8 ? `${s.slice(0, 4)}••••${s.slice(-4)}` : s);
    }
    // Crypto address
    const rAddr = tx.metadata?.to_address || tx.metadata?.to_wallet_address || tx.metadata?.receiver_crypto_address;
    if (rAddr) {
      const a = String(rAddr);
      receiverDetails.push(`${a.slice(0, 6)}••••${a.slice(-4)}`);
    }
    // Card number
    const rCard = tx.metadata?.receiver_card_number || tx.metadata?.to_card_number || tx.metadata?.card_number || tx.metadata?.to_card_mask;
    if (rCard) {
      const c = String(rCard);
      receiverDetails.push(`•••• ${c.slice(-4)}`);
    }
    // Movements fallback - check ALL movements for receiver data
    if (receiverDetails.length === 0 && tx.movements && Array.isArray(tx.movements)) {
      // Try index 1 first, then any movement with account_type 'card' or 'bank'
      const candidates = tx.movements.length > 1 ? [tx.movements[1], ...tx.movements] : tx.movements;
      for (const m of candidates) {
        if (receiverDetails.length > 0) break;
        if (m.card_mask) receiverDetails.push(`•••• ${m.card_mask.slice(-4)}`);
        else if (m.card_number) { const c = String(m.card_number); receiverDetails.push(`•••• ${c.slice(-4)}`); }
        else if (m.iban) { const i = String(m.iban); receiverDetails.push(`${i.slice(0, 4)}••••${i.slice(-4)}`); }
        else if (m.address) { const a = String(m.address); receiverDetails.push(`${a.slice(0, 6)}••••${a.slice(-4)}`); }
      }
    }
    // Last resort: use display subtitle
    if (receiverDetails.length === 0 && tx.display?.subtitle) {
      const sub = String(tx.display.subtitle);
      const cardMatch = sub.match(/(\d{4})\s*$/);
      if (cardMatch) receiverDetails.push(`•••• ${cardMatch[1]}`);
    }
    
    const senderMask = senderDetails.length > 0 ? esc(senderDetails.join(' · ')) : '—';
    const receiverMask = receiverDetails.length > 0 ? esc(receiverDetails.join(' · ')) : '—';
    const fee = tx.fee !== undefined && tx.fee !== null ? `${tx.fee} ${currency}` : '—';

    return `<tr>
      <td class="num">${idx + 1}</td>
      <td class="date-cell">${esc(date)}<br><span class="time">${esc(time)}</span></td>
      <td><span class="type-badge">${esc(type)}</span></td>
      <td class="desc">${description || '—'}</td>
      <td class="amount ${amountClass}">${esc(amount)} ${esc(currency)}</td>
      <td><span class="status-dot" style="background:${st.color}"></span>${esc(st.label)}</td>
      <td class="participant">${senderName}<br><span class="card-mask">${senderMask}</span></td>
      <td class="participant">${receiverName}<br><span class="card-mask">${receiverMask}</span></td>
      <td class="fee">${esc(fee)}</td>
    </tr>`;
  }).join('\n');

  return `<!DOCTYPE html>
<html lang="${lang}">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>uEasyCard — ${t(lang, 'reportTitle')}</title>
<style>
  @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap');
  
  * { margin: 0; padding: 0; box-sizing: border-box; }
  
  body {
    font-family: 'Inter', -apple-system, sans-serif;
    background: #f8fafc;
    color: #1e293b;
    line-height: 1.5;
  }
  
  .page {
    max-width: 1200px;
    margin: 0 auto;
    padding: 0;
    background: #fff;
    min-height: 100vh;
  }
  
  /* ===== HEADER ===== */
  .header {
    background: linear-gradient(135deg, #000000 0%, #0a0a0a 40%, #007AFF 100%);
    color: #fff;
    padding: 40px 48px;
    position: relative;
    overflow: hidden;
  }
  
  .header::before {
    content: '';
    position: absolute;
    top: -50%;
    right: -20%;
    width: 500px;
    height: 500px;
    background: radial-gradient(circle, rgba(0,122,255,0.3) 0%, transparent 70%);
    border-radius: 50%;
  }
  
  .header::after {
    content: '';
    position: absolute;
    bottom: -30%;
    left: 10%;
    width: 300px;
    height: 300px;
    background: radial-gradient(circle, rgba(0,122,255,0.2) 0%, transparent 70%);
    border-radius: 50%;
  }
  
  .header-content {
    position: relative;
    z-index: 1;
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
  }
  
  .brand {
    display: flex;
    align-items: center;
    gap: 16px;
    margin-bottom: 24px;
  }
  
  .logo-svg {
    width: 56px;
    height: 56px;
    flex-shrink: 0;
  }
  
  .brand-name {
    font-size: 28px;
    font-weight: 800;
    letter-spacing: -0.5px;
  }
  
  .brand-name .u-letter { color: #007AFF; }
  
  .report-title {
    font-size: 18px;
    font-weight: 600;
    opacity: 0.9;
    margin-bottom: 6px;
  }
  
  .report-period {
    font-size: 32px;
    font-weight: 800;
    letter-spacing: -1px;
    color: #fff;
  }
  
  .balances-row {
    display: flex;
    gap: 10px;
    margin-top: 16px;
    flex-wrap: nowrap;
    white-space: nowrap;
  }
  
  .balance-chip {
    display: inline-flex;
    align-items: center;
    gap: 4px;
    background: rgba(255,255,255,0.12);
    border: 1px solid rgba(255,255,255,0.15);
    border-radius: 8px;
    padding: 5px 10px;
    font-size: 12px;
    backdrop-filter: blur(4px);
    white-space: nowrap;
    flex-shrink: 0;
  }
  
  .balance-chip .bal-label {
    opacity: 0.7;
    font-weight: 500;
  }
  
  .balance-chip .bal-value {
    font-weight: 700;
    letter-spacing: -0.3px;
  }
    text-align: right;
    font-size: 13px;
    opacity: 0.75;
    line-height: 1.8;
  }
  
  .header-meta strong {
    display: block;
    font-size: 14px;
    opacity: 1;
    color: #fff;
  }
  
  /* ===== SUMMARY CARDS ===== */
  .summary {
    display: grid;
    grid-template-columns: repeat(4, 1fr);
    gap: 16px;
    padding: 24px 48px;
    margin-top: -28px;
    position: relative;
    z-index: 2;
  }
  
  .summary-card {
    background: #fff;
    border-radius: 16px;
    padding: 20px 24px;
    box-shadow: 0 4px 24px rgba(0,0,0,0.08);
    border: 1px solid #e2e8f0;
  }
  
  .summary-card .label {
    font-size: 12px;
    font-weight: 600;
    color: #94a3b8;
    text-transform: uppercase;
    letter-spacing: 0.5px;
    margin-bottom: 8px;
  }
  
  .summary-card .value {
    font-size: 24px;
    font-weight: 800;
    letter-spacing: -0.5px;
  }
  
  .summary-card.income .value { color: #10b981; }
  .summary-card.expense .value { color: #ef4444; }
  .summary-card.balance .value { color: #007AFF; }
  .summary-card.count .value { color: #1e293b; }
  
  /* ===== TABLE ===== */
  .table-wrapper {
    padding: 24px 48px 48px;
    overflow-x: auto;
  }
  
  .table-title {
    font-size: 16px;
    font-weight: 700;
    color: #1e293b;
    margin-bottom: 16px;
    display: flex;
    align-items: center;
    gap: 8px;
  }
  
  .table-title::before {
    content: '';
    width: 4px;
    height: 20px;
    background: linear-gradient(180deg, #007AFF, #5AC8FA);
    border-radius: 2px;
  }
  
  table {
    width: 100%;
    border-collapse: separate;
    border-spacing: 0;
    font-size: 13px;
  }
  
  thead th {
    background: #f1f5f9;
    color: #64748b;
    font-weight: 600;
    font-size: 11px;
    text-transform: uppercase;
    letter-spacing: 0.5px;
    padding: 12px 14px;
    text-align: left;
    white-space: nowrap;
    border-bottom: 2px solid #e2e8f0;
  }
  
  thead th:first-child { border-radius: 10px 0 0 0; }
  thead th:last-child { border-radius: 0 10px 0 0; }
  
  tbody tr {
    transition: background 0.15s;
  }
  
  tbody tr:hover { background: #f8fafc; }
  tbody tr:nth-child(even) { background: #fafbfc; }
  tbody tr:nth-child(even):hover { background: #f1f5f9; }
  
  td {
    padding: 12px 14px;
    border-bottom: 1px solid #f1f5f9;
    vertical-align: middle;
  }
  
  .num {
    color: #94a3b8;
    font-weight: 500;
    text-align: center;
    width: 40px;
  }
  
  .date-cell { white-space: nowrap; font-weight: 500; }
  .time { color: #94a3b8; font-size: 11px; }
  
  .type-badge {
    display: inline-block;
    background: #eff6ff;
    color: #3b82f6;
    padding: 3px 10px;
    border-radius: 6px;
    font-size: 11px;
    font-weight: 600;
    white-space: nowrap;
  }
  
  .desc { max-width: 200px; }
  .sub { color: #94a3b8; font-size: 11px; }
  
  .amount {
    font-weight: 700;
    white-space: nowrap;
    font-variant-numeric: tabular-nums;
  }
  
  .amount-in { color: #10b981; }
  .amount-out { color: #ef4444; }
  
  .status-dot {
    display: inline-block;
    width: 8px;
    height: 8px;
    border-radius: 50%;
    margin-right: 6px;
    vertical-align: middle;
  }
  
  .participant {
    font-size: 12px;
    max-width: 140px;
  }
  
  .card-mask {
    color: #94a3b8;
    font-size: 11px;
    font-family: 'SF Mono', 'Fira Code', monospace;
  }
  
  .fee {
    color: #94a3b8;
    font-size: 12px;
    white-space: nowrap;
  }
  
  /* ===== FOOTER ===== */
  .footer {
    padding: 32px 48px;
    background: #f8fafc;
    border-top: 1px solid #e2e8f0;
    display: flex;
    justify-content: space-between;
    align-items: center;
    font-size: 12px;
    color: #94a3b8;
  }
  
  .footer-brand {
    font-weight: 700;
    color: #64748b;
  }
  
  /* Print styles */
  @media print {
    body { background: #fff; }
    .page { box-shadow: none; }
    .summary-card { box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
    .header { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
    @page { margin: 0; size: A4 landscape; }
  }
</style>
</head>
<body>
<div class="page">
  <!-- HEADER -->
  <div class="header">
    <div class="header-content">
      <div>
        <div class="brand">
          <svg class="logo-svg" viewBox="0 0 512 512" fill="none" xmlns="http://www.w3.org/2000/svg">
            <rect width="512" height="512" rx="62" fill="black"/>
            <path d="M259 66.002L301.399 66V266.83C301.399 289.38 296.013 309.111 285.242 326.023C274.571 342.935 259.622 356.122 240.394 365.585C221.167 374.947 198.769 379.628 173.199 379.628C147.529 379.628 125.081 374.947 105.853 365.585C86.6258 356.122 71.6767 342.935 61.006 326.023C50.3353 309.111 45 289.38 45 266.83V66H110.383V261.243C110.383 273.021 112.95 283.491 118.084 292.651C123.319 301.812 130.668 309.01 140.13 314.245C149.593 319.479 160.616 322.097 173.199 322.097C185.883 322.097 196.906 319.479 206.268 314.245C215.731 309.01 223.029 301.812 228.163 292.651C233.398 283.491 236.015 273.021 236.015 261.243L259 66.002Z" fill="white"/>
            <path d="M259 379.002V66.002H467.381V120.563H324.383V195.145H456.659V249.706H324.383V324.441H467.985V379.002H259Z" fill="url(#paint0_radial)"/>
            <path d="M142.852 414.35H119.597C119.172 413.031 118.305 411.858 116.995 410.834C115.686 409.793 114.004 408.908 111.951 408.179C109.898 407.449 107.527 406.89 104.837 406.502C102.182 406.114 99.2974 405.92 96.1826 405.92C90.5546 405.92 85.6523 406.533 81.4755 407.76C77.2988 408.971 74.0601 410.74 71.7593 413.069C69.4586 415.383 68.3082 418.193 68.3082 421.5C68.3082 424.9 69.4586 427.757 71.7593 430.07C74.0955 432.384 77.3519 434.13 81.5286 435.31C85.7054 436.49 90.5369 437.08 96.0233 437.08C99.1027 437.08 101.952 436.902 104.571 436.545C107.226 436.188 109.58 435.667 111.633 434.984C113.686 434.286 115.385 433.439 116.73 432.446C118.11 431.452 119.066 430.319 119.597 429.046L142.852 429.092C142.25 431.281 140.746 433.393 138.339 435.427C135.968 437.445 132.764 439.254 128.729 440.853C124.729 442.437 119.951 443.694 114.394 444.626C108.872 445.542 102.625 446 95.6516 446C85.9531 446 77.2811 445.037 69.6356 443.112C62.0255 441.187 56.0081 438.4 51.5836 434.751C47.1945 431.103 45 426.686 45 421.5C45 416.299 47.2299 411.874 51.6898 408.225C56.1497 404.577 62.2024 401.798 69.848 399.888C77.4935 397.963 86.0947 397 95.6516 397C101.952 397 107.792 397.388 113.173 398.164C118.588 398.941 123.384 400.074 127.561 401.565C131.738 403.04 135.136 404.848 137.755 406.991C140.41 409.134 142.109 411.587 142.852 414.35Z" fill="white"/>
            <path d="M176.036 445.348H151.4L188.938 397.652H218.564L256.048 445.348H231.413L204.176 408.551H203.326L176.036 445.348ZM174.496 426.6H232.687V434.472H174.496V426.6Z" fill="white"/>
            <path d="M269.136 445.348V397.652H312.036C320.248 397.652 327.256 398.296 333.061 399.585C338.901 400.858 343.344 402.667 346.388 405.011C349.467 407.34 351.007 410.081 351.007 413.232C351.007 416.4 349.45 419.125 346.335 421.407C343.22 423.674 338.707 425.413 332.796 426.624C326.92 427.835 319.805 428.44 311.452 428.44H282.728V420.336H307.735C312.124 420.336 315.77 420.072 318.673 419.544C321.575 419.016 323.734 418.224 325.15 417.168C326.601 416.112 327.327 414.801 327.327 413.232C327.327 411.649 326.601 410.314 325.15 409.227C323.734 408.14 321.557 407.317 318.62 406.758C315.717 406.184 312.054 405.896 307.629 405.896H292.126V445.348H269.136ZM327.858 423.643L354.883 445.348H329.504L303.063 423.643H327.858Z" fill="white"/>
            <path d="M405.8 445.348H367.254V397.652H406.118C417.056 397.652 426.471 398.607 434.364 400.517C442.258 402.411 448.328 405.136 452.576 408.691C456.859 412.247 459 416.501 459 421.453C459 426.422 456.859 430.691 452.576 434.262C448.328 437.833 442.222 440.574 434.258 442.483C426.33 444.393 416.843 445.348 405.8 445.348ZM390.243 436.708H404.844C411.64 436.708 417.357 436.18 421.994 435.124C426.666 434.053 430.17 432.399 432.506 430.163C434.878 427.912 436.063 425.009 436.063 421.453C436.063 417.929 434.878 415.049 432.506 412.813C430.17 410.577 426.683 408.932 422.047 407.876C417.41 406.82 411.693 406.292 404.897 406.292H390.243V436.708Z" fill="white"/>
            <defs>
              <radialGradient id="paint0_radial" cx="0" cy="0" r="1" gradientUnits="userSpaceOnUse" gradientTransform="translate(256.492 222.814) rotate(90) scale(156.814 211.492)">
                <stop offset="0.399038" stop-color="white"/>
                <stop offset="1" stop-color="#462375"/>
              </radialGradient>
            </defs>
          </svg>
          <div class="brand-name"><span class="u-letter">u</span>EasyCard</div>
        </div>
        <div class="report-title">${t(lang, 'reportTitle')}</div>
        <div class="report-period">${esc(periodLabel)}</div>
        ${assetBalances.length > 0 ? `
        <div class="balances-row">
          ${assetBalances.map(b => `
            <div class="balance-chip">
              <span class="bal-label">${esc(b.label)}:</span>
              <span class="bal-value">${esc(b.amount)} ${esc(b.currency)}</span>
            </div>
          `).join('')}
        </div>` : ''}
      </div>
      <div class="header-meta">
        ${userName ? `<strong>${esc(userName)}</strong>` : ''}
        ${t(lang, 'generatedOn')}: ${esc(generatedDate)}<br>
        ${t(lang, 'autoGenerated')}<br>
        uEasyCard Financial Services
      </div>
    </div>
  </div>

  <!-- SUMMARY -->
  <div class="summary">
    <div class="summary-card count">
      <div class="label">${t(lang, 'totalOps')}</div>
      <div class="value">${filtered.length}</div>
    </div>
    <div class="summary-card income">
      <div class="label">${t(lang, 'income')}</div>
      <div class="value">+${totalIn.toLocaleString(locale, { minimumFractionDigits: 2 })} AED</div>
    </div>
    <div class="summary-card expense">
      <div class="label">${t(lang, 'expense')}</div>
      <div class="value">-${totalOut.toLocaleString(locale, { minimumFractionDigits: 2 })} AED</div>
    </div>
    <div class="summary-card balance">
      <div class="label">${t(lang, 'balance')}</div>
      <div class="value">${(totalIn - totalOut).toLocaleString(locale, { minimumFractionDigits: 2 })} AED</div>
    </div>
  </div>

  <!-- TABLE -->
  <div class="table-wrapper">
    <div class="table-title">${t(lang, 'detailTitle')}</div>
    <table>
      <thead>
        <tr>
          <th>${t(lang, 'num')}</th>
          <th>${t(lang, 'date')}</th>
          <th>${t(lang, 'type')}</th>
          <th>${t(lang, 'description')}</th>
          <th>${t(lang, 'amount')}</th>
          <th>${t(lang, 'status')}</th>
          <th>${t(lang, 'sender')}</th>
          <th>${t(lang, 'receiver')}</th>
          <th>${t(lang, 'fee')}</th>
        </tr>
      </thead>
      <tbody>
        ${txRows}
      </tbody>
    </table>
  </div>

  <!-- FOOTER -->
  <div class="footer">
    <div class="footer-brand">uEasyCard © ${new Date().getFullYear()}</div>
    <div>Конфиденциальный документ · Только для личного использования</div>
  </div>
</div>
</body>
</html>`;
}

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { backend_token, start_date, end_date, user_name, asset_filter, lang: rawLang } = await req.json();
    const lang: Lang = (['ru','en','de','tr','zh','ar','es'].includes(rawLang) ? rawLang : 'en') as Lang;
    const locale = getLocale(lang);
    const filterAssets = Array.isArray(asset_filter) && asset_filter.length > 0 ? asset_filter : null;

    if (!backend_token) {
      return new Response(
        JSON.stringify({ error: t(lang, 'notAuthorized') }),
        { status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const BACKEND_BASE = "https://ueasycard.com/api/v1";
    const headers = {
      "Content-Type": "application/json",
      "Authorization": `Token ${backend_token}`,
    };

    // Fetch transactions and balances in parallel
    const [response, walletRes, bankRes, cryptoRes] = await Promise.all([
      fetch(`${BACKEND_BASE}/transactions/all/`, { method: "GET", headers }),
      fetch(`${BACKEND_BASE}/cards/wallet/summary/`, { method: "GET", headers }).catch(() => null),
      fetch(`${BACKEND_BASE}/transactions/bank-accounts/`, { method: "GET", headers }).catch(() => null),
      fetch(`${BACKEND_BASE}/transactions/crypto-wallets/`, { method: "GET", headers }).catch(() => null),
    ]);

    if (!response.ok) {
      console.error("Transactions API error:", response.status);
      return new Response(
        JSON.stringify({ error: t(lang, 'fetchError') }),
        { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Parse balances
    const assetBalances: AssetBalance[] = [];
    const includeCards = !filterAssets || filterAssets.includes('card');
    const includeIban = !filterAssets || filterAssets.includes('iban');
    const includeCrypto = !filterAssets || filterAssets.includes('crypto');

    try {
      if (walletRes?.ok) {
        const wallet = await walletRes.json();
        // Cards balances
        if (includeCards && wallet.cards && Array.isArray(wallet.cards)) {
          for (const card of wallet.cards) {
            const bal = parseFloat(String(card.balance || 0));
            if (bal > 0 || card.card_mask) {
              const rawType = card.card_type || card.type || t(lang, 'card');
              const cardType = rawType.charAt(0).toUpperCase() + rawType.slice(1).toLowerCase();
              const mask = card.card_mask ? `•••• ${String(card.card_mask).slice(-4)}` : '';
              assetBalances.push({ label: `${cardType} ${mask}`.trim(), amount: bal.toLocaleString(locale, { minimumFractionDigits: 2 }), currency: 'AED' });
            }
          }
        }
        // USDT balance
        if (includeCrypto && wallet.usdt_balance !== undefined) {
          const usdtBal = parseFloat(String(wallet.usdt_balance || 0));
          assetBalances.push({ label: `${t(lang, 'wallet')} USDT`, amount: usdtBal.toLocaleString(locale, { minimumFractionDigits: 2 }), currency: 'USDT' });
        }
      }
    } catch (e) { console.error("Wallet parse error:", e); }

    try {
      if (includeIban && bankRes?.ok) {
        const bankData = await bankRes.json();
        const accounts = Array.isArray(bankData) ? bankData : (bankData?.results || []);
        for (const acc of accounts) {
          const bal = parseFloat(String(acc.balance || 0));
          const iban = acc.iban ? `${String(acc.iban).slice(0, 4)}••••${String(acc.iban).slice(-4)}` : 'IBAN';
          assetBalances.push({ label: `${t(lang, 'account')} ${iban}`, amount: bal.toLocaleString(locale, { minimumFractionDigits: 2 }), currency: acc.currency || 'AED' });
        }
      }
    } catch (e) { console.error("Bank parse error:", e); }

    try {
      if (includeCrypto && cryptoRes?.ok) {
        const cryptoData = await cryptoRes.json();
        const wallets = Array.isArray(cryptoData) ? cryptoData : (cryptoData?.results || []);
        for (const w of wallets) {
          const bal = parseFloat(String(w.balance || 0));
          const token = w.token || 'USDT';
          if (token === 'USDT' && assetBalances.some(a => a.label.includes('USDT'))) continue;
          assetBalances.push({ label: `${t(lang, 'wallet')} ${token}`, amount: bal.toLocaleString(locale, { minimumFractionDigits: 2 }), currency: token });
        }
      }
    } catch (e) { console.error("Crypto parse error:", e); }

    const rawData = await response.json();
    const allTransactions = Array.isArray(rawData) ? rawData : (rawData?.results || rawData?.data || []);

    let filtered = allTransactions;
    if (start_date || end_date) {
      const startMs = start_date ? new Date(start_date).getTime() : 0;
      const endMs = end_date ? new Date(end_date + "T23:59:59").getTime() : Date.now();
      filtered = allTransactions.filter((tx: any) => {
        const txDate = new Date(tx.created_at).getTime();
        return txDate >= startMs && txDate <= endMs;
      });
    }

    // Filter by asset type if specified
    if (filterAssets) {
      filtered = filtered.filter((tx: any) => {
        const txType = String(tx.type || '').toLowerCase();
        const currency = String(tx.currency || tx.display?.primary_amount?.currency || '').toUpperCase();
        
        // Card transactions
        if (includeCards) {
          if (txType === 'card_payment' || txType === 'card_activation' || txType === 'card_transfer' || txType === 'payment') return true;
          if (tx.card_id) return true;
          // Top-ups that go to cards
          if (txType === 'top_up' || txType === 'topup') return true;
        }
        
        // IBAN / bank transactions
        if (includeIban) {
          if (txType.includes('bank') || txType.includes('iban') || txType === 'withdrawal') return true;
          if (txType === 'transfer_in' || txType === 'transfer_out' || txType === 'internal_transfer') return true;
        }
        
        // Crypto transactions
        if (includeCrypto) {
          if (txType.includes('crypto')) return true;
          if (currency === 'USDT' || currency === 'BTC' || currency === 'ETH') return true;
        }
        
        // If transaction type doesn't clearly match any category, include if all types selected
        return false;
      });
    }

    const totalIn = filtered
      .filter((tx: any) => {
        const sign = tx.display?.primary_amount?.sign;
        const amt = parseFloat(String(tx.display?.primary_amount?.amount || tx.amount || 0).replace(/,/g, ''));
        return sign === '+' || (!sign && amt > 0);
      })
      .reduce((sum: number, tx: any) => {
        const amt = parseFloat(String(tx.display?.primary_amount?.amount || tx.amount || 0).replace(/,/g, ''));
        return sum + (isNaN(amt) ? 0 : Math.abs(amt));
      }, 0);

    const totalOut = filtered
      .filter((tx: any) => {
        const sign = tx.display?.primary_amount?.sign;
        const amt = parseFloat(String(tx.display?.primary_amount?.amount || tx.amount || 0).replace(/,/g, ''));
        return sign === '-' || (!sign && amt < 0);
      })
      .reduce((sum: number, tx: any) => {
        const amt = parseFloat(String(tx.display?.primary_amount?.amount || tx.amount || 0).replace(/,/g, ''));
        return sum + (isNaN(amt) ? 0 : Math.abs(amt));
      }, 0);

    const periodLabel = start_date && end_date
      ? `${formatDate(start_date)} — ${formatDate(end_date)}`
      : start_date
        ? `${t(lang, 'from')} ${formatDate(start_date)}`
        : end_date
          ? `${t(lang, 'to')} ${formatDate(end_date)}`
          : t(lang, 'allTx');

    const generatedDate = formatDate(new Date().toISOString());
    const html = buildHTML(filtered, periodLabel, user_name || '', generatedDate, totalIn, totalOut, assetBalances, lang);

    const fileDate = new Date().toISOString().slice(0, 10).replace(/-/g, '');
    const fileName = `uEasyCard_Report_${fileDate}.html`;

    return new Response(html, {
      headers: {
        ...corsHeaders,
        "Content-Type": "text/html; charset=utf-8",
        "Content-Disposition": `attachment; filename="${fileName}"`,
      },
    });
  } catch (error) {
    console.error("Report generation error:", error);
    return new Response(
      JSON.stringify({ error: "Ошибка при формировании отчёта" }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
