import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { jsPDF } from "npm:jspdf@2.5.2";
import "npm:jspdf-autotable@3.8.4";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

function formatDate(dateStr: string): string {
  const date = new Date(dateStr);
  return `${date.getDate().toString().padStart(2, '0')}.${(date.getMonth() + 1).toString().padStart(2, '0')}.${date.getFullYear()}`;
}

function formatTime(dateStr: string): string {
  const date = new Date(dateStr);
  return `${date.getHours().toString().padStart(2, '0')}:${date.getMinutes().toString().padStart(2, '0')}`;
}

// ─── i18n translations ───
type Lang = 'ru' | 'en' | 'de' | 'tr' | 'zh' | 'ar' | 'es';

const i18n: Record<Lang, Record<string, string>> = {
  ru: {
    reportTitle: 'Отчёт по транзакциям', generatedOn: 'Дата формирования', autoGenerated: 'Документ сформирован автоматически',
    totalOps: 'Всего операций', income: 'Приход', expense: 'Расход', balance: 'Баланс',
    detailTitle: 'Детализация операций', num: '№', date: 'Дата', type: 'Тип', description: 'Описание',
    amount: 'Сумма', status: 'Статус', sender: 'Отправитель', receiver: 'Получатель', fee: 'Комиссия',
    allTx: 'Все транзакции', from: 'с', to: 'по', wallet: 'Кошелёк', account: 'Счёт', card: 'Карта',
    notAuthorized: 'Не авторизован', fetchError: 'Не удалось получить транзакции', genError: 'Ошибка при формировании отчёта',
    pending: 'В обработке', processing: 'Обрабатывается', settled: 'Завершено', completed: 'Завершено',
    failed: 'Ошибка', cancelled: 'Отменено', declined: 'Отклонено',
    top_up: 'Пополнение', withdrawal: 'Вывод', transfer_in: 'Входящий перевод', transfer_out: 'Исходящий перевод',
    card_payment: 'Оплата картой', refund: 'Возврат', fee_type: 'Комиссия', cashback: 'Кэшбэк',
    card_activation: 'Активация карты', card_transfer: 'Перевод между картами', bank_transfer: 'Банковский перевод',
    bank_transfer_incoming: 'Входящий банк. перевод', crypto_withdrawal: 'Вывод крипто', crypto_send: 'Отправка крипто',
    crypto_deposit: 'Пополнение крипто', crypto_to_card: 'Крипто → Карта', crypto_to_iban: 'Крипто → IBAN',
    crypto_to_crypto: 'Крипто → Крипто', bank_to_crypto: 'Банк → Крипто', iban_to_iban: 'IBAN → IBAN',
    internal_transfer: 'Внутренний перевод', payment: 'Платёж',
    confidential: 'Конфиденциальный документ · Только для личного использования',
  },
  en: {
    reportTitle: 'Transaction Report', generatedOn: 'Generated on', autoGenerated: 'Document generated automatically',
    totalOps: 'Total operations', income: 'Income', expense: 'Expense', balance: 'Balance',
    detailTitle: 'Transaction Details', num: '#', date: 'Date', type: 'Type', description: 'Description',
    amount: 'Amount', status: 'Status', sender: 'Sender', receiver: 'Receiver', fee: 'Fee',
    allTx: 'All transactions', from: 'from', to: 'to', wallet: 'Wallet', account: 'Account', card: 'Card',
    notAuthorized: 'Not authorized', fetchError: 'Failed to fetch transactions', genError: 'Report generation error',
    pending: 'Pending', processing: 'Processing', settled: 'Settled', completed: 'Completed',
    failed: 'Failed', cancelled: 'Cancelled', declined: 'Declined',
    top_up: 'Top Up', withdrawal: 'Withdrawal', transfer_in: 'Incoming Transfer', transfer_out: 'Outgoing Transfer',
    card_payment: 'Card Payment', refund: 'Refund', fee_type: 'Fee', cashback: 'Cashback',
    card_activation: 'Card Activation', card_transfer: 'Card Transfer', bank_transfer: 'Bank Transfer',
    bank_transfer_incoming: 'Incoming Bank Transfer', crypto_withdrawal: 'Crypto Withdrawal', crypto_send: 'Crypto Send',
    crypto_deposit: 'Crypto Deposit', crypto_to_card: 'Crypto → Card', crypto_to_iban: 'Crypto → IBAN',
    crypto_to_crypto: 'Crypto → Crypto', bank_to_crypto: 'Bank → Crypto', iban_to_iban: 'IBAN → IBAN',
    internal_transfer: 'Internal Transfer', payment: 'Payment',
    confidential: 'Confidential document · For personal use only',
  },
  de: {
    reportTitle: 'Transaktionsbericht', generatedOn: 'Erstellt am', autoGenerated: 'Dokument automatisch erstellt',
    totalOps: 'Gesamtoperationen', income: 'Einnahmen', expense: 'Ausgaben', balance: 'Saldo',
    detailTitle: 'Transaktionsdetails', num: 'Nr.', date: 'Datum', type: 'Typ', description: 'Beschreibung',
    amount: 'Betrag', status: 'Status', sender: 'Absender', receiver: 'Empfänger', fee: 'Gebühr',
    allTx: 'Alle Transaktionen', from: 'von', to: 'bis', wallet: 'Wallet', account: 'Konto', card: 'Karte',
    notAuthorized: 'Nicht autorisiert', fetchError: 'Transaktionen konnten nicht abgerufen werden', genError: 'Fehler bei der Berichterstellung',
    pending: 'Ausstehend', processing: 'In Bearbeitung', settled: 'Abgeschlossen', completed: 'Abgeschlossen',
    failed: 'Fehlgeschlagen', cancelled: 'Storniert', declined: 'Abgelehnt',
    top_up: 'Aufladung', withdrawal: 'Auszahlung', transfer_in: 'Eingehende Überweisung', transfer_out: 'Ausgehende Überweisung',
    card_payment: 'Kartenzahlung', refund: 'Rückerstattung', fee_type: 'Gebühr', cashback: 'Cashback',
    card_activation: 'Kartenaktivierung', card_transfer: 'Kartenüberweisung', bank_transfer: 'Banküberweisung',
    bank_transfer_incoming: 'Eingehende Banküberweisung', crypto_withdrawal: 'Krypto-Auszahlung', crypto_send: 'Krypto-Versand',
    crypto_deposit: 'Krypto-Einzahlung', crypto_to_card: 'Krypto → Karte', crypto_to_iban: 'Krypto → IBAN',
    crypto_to_crypto: 'Krypto → Krypto', bank_to_crypto: 'Bank → Krypto', iban_to_iban: 'IBAN → IBAN',
    internal_transfer: 'Interne Überweisung', payment: 'Zahlung',
    confidential: 'Vertrauliches Dokument · Nur für den persönlichen Gebrauch',
  },
  tr: {
    reportTitle: 'İşlem Raporu', generatedOn: 'Oluşturulma tarihi', autoGenerated: 'Belge otomatik olarak oluşturuldu',
    totalOps: 'Toplam işlem', income: 'Gelir', expense: 'Gider', balance: 'Bakiye',
    detailTitle: 'İşlem Detayları', num: 'No', date: 'Tarih', type: 'Tür', description: 'Açıklama',
    amount: 'Tutar', status: 'Durum', sender: 'Gönderen', receiver: 'Alıcı', fee: 'Komisyon',
    allTx: 'Tüm işlemler', from: 'den', to: 'e', wallet: 'Cüzdan', account: 'Hesap', card: 'Kart',
    notAuthorized: 'Yetkisiz', fetchError: 'İşlemler alınamadı', genError: 'Rapor oluşturma hatası',
    pending: 'Beklemede', processing: 'İşleniyor', settled: 'Tamamlandı', completed: 'Tamamlandı',
    failed: 'Başarısız', cancelled: 'İptal edildi', declined: 'Reddedildi',
    top_up: 'Yükleme', withdrawal: 'Çekim', transfer_in: 'Gelen Transfer', transfer_out: 'Giden Transfer',
    card_payment: 'Kart Ödeme', refund: 'İade', fee_type: 'Komisyon', cashback: 'Cashback',
    card_activation: 'Kart Aktivasyonu', card_transfer: 'Kartlar Arası Transfer', bank_transfer: 'Banka Transferi',
    bank_transfer_incoming: 'Gelen Banka Transferi', crypto_withdrawal: 'Kripto Çekim', crypto_send: 'Kripto Gönderim',
    crypto_deposit: 'Kripto Yükleme', crypto_to_card: 'Kripto → Kart', crypto_to_iban: 'Kripto → IBAN',
    crypto_to_crypto: 'Kripto → Kripto', bank_to_crypto: 'Banka → Kripto', iban_to_iban: 'IBAN → IBAN',
    internal_transfer: 'Dahili Transfer', payment: 'Ödeme',
    confidential: 'Gizli belge · Yalnızca kişisel kullanım için',
  },
  zh: {
    reportTitle: '交易报告', generatedOn: '生成日期', autoGenerated: '文件自动生成',
    totalOps: '总操作数', income: '收入', expense: '支出', balance: '余额',
    detailTitle: '交易明细', num: '序号', date: '日期', type: '类型', description: '描述',
    amount: '金额', status: '状态', sender: '发送方', receiver: '接收方', fee: '手续费',
    allTx: '所有交易', from: '从', to: '至', wallet: '钱包', account: '账户', card: '卡',
    notAuthorized: '未授权', fetchError: '无法获取交易', genError: '报告生成错误',
    pending: '待处理', processing: '处理中', settled: '已完成', completed: '已完成',
    failed: '失败', cancelled: '已取消', declined: '已拒绝',
    top_up: '充值', withdrawal: '提现', transfer_in: '转入', transfer_out: '转出',
    card_payment: '卡支付', refund: '退款', fee_type: '手续费', cashback: '返现',
    card_activation: '卡激活', card_transfer: '卡间转账', bank_transfer: '银行转账',
    bank_transfer_incoming: '银行转入', crypto_withdrawal: '加密提现', crypto_send: '加密发送',
    crypto_deposit: '加密充值', crypto_to_card: '加密 → 卡', crypto_to_iban: '加密 → IBAN',
    crypto_to_crypto: '加密 → 加密', bank_to_crypto: '银行 → 加密', iban_to_iban: 'IBAN → IBAN',
    internal_transfer: '内部转账', payment: '支付',
    confidential: '机密文件 · 仅供个人使用',
  },
  ar: {
    reportTitle: 'تقرير المعاملات', generatedOn: 'تاريخ الإنشاء', autoGenerated: 'تم إنشاء المستند تلقائياً',
    totalOps: 'إجمالي العمليات', income: 'الدخل', expense: 'المصروفات', balance: 'الرصيد',
    detailTitle: 'تفاصيل المعاملات', num: 'رقم', date: 'التاريخ', type: 'النوع', description: 'الوصف',
    amount: 'المبلغ', status: 'الحالة', sender: 'المرسل', receiver: 'المستلم', fee: 'العمولة',
    allTx: 'جميع المعاملات', from: 'من', to: 'إلى', wallet: 'محفظة', account: 'حساب', card: 'بطاقة',
    notAuthorized: 'غير مصرح', fetchError: 'تعذر جلب المعاملات', genError: 'خطأ في إنشاء التقرير',
    pending: 'قيد الانتظار', processing: 'جاري المعالجة', settled: 'مكتمل', completed: 'مكتمل',
    failed: 'فشل', cancelled: 'ملغى', declined: 'مرفوض',
    top_up: 'إيداع', withdrawal: 'سحب', transfer_in: 'تحويل وارد', transfer_out: 'تحويل صادر',
    card_payment: 'دفع بالبطاقة', refund: 'استرداد', fee_type: 'عمولة', cashback: 'استرداد نقدي',
    card_activation: 'تفعيل البطاقة', card_transfer: 'تحويل بين البطاقات', bank_transfer: 'تحويل بنكي',
    bank_transfer_incoming: 'تحويل بنكي وارد', crypto_withdrawal: 'سحب كريبتو', crypto_send: 'إرسال كريبتو',
    crypto_deposit: 'إيداع كريبتو', crypto_to_card: 'كريبتو → بطاقة', crypto_to_iban: 'كريبتو → IBAN',
    crypto_to_crypto: 'كريبتو → كريبتو', bank_to_crypto: 'بنك → كريبتو', iban_to_iban: 'IBAN → IBAN',
    internal_transfer: 'تحويل داخلي', payment: 'دفعة',
    confidential: 'مستند سري · للاستخدام الشخصي فقط',
  },
  es: {
    reportTitle: 'Informe de Transacciones', generatedOn: 'Fecha de generación', autoGenerated: 'Documento generado automáticamente',
    totalOps: 'Total operaciones', income: 'Ingresos', expense: 'Gastos', balance: 'Saldo',
    detailTitle: 'Detalle de Operaciones', num: 'Nº', date: 'Fecha', type: 'Tipo', description: 'Descripción',
    amount: 'Monto', status: 'Estado', sender: 'Remitente', receiver: 'Destinatario', fee: 'Comisión',
    allTx: 'Todas las transacciones', from: 'desde', to: 'hasta', wallet: 'Billetera', account: 'Cuenta', card: 'Tarjeta',
    notAuthorized: 'No autorizado', fetchError: 'No se pudieron obtener las transacciones', genError: 'Error al generar el informe',
    pending: 'Pendiente', processing: 'Procesando', settled: 'Completado', completed: 'Completado',
    failed: 'Fallido', cancelled: 'Cancelado', declined: 'Rechazado',
    top_up: 'Recarga', withdrawal: 'Retiro', transfer_in: 'Transferencia entrante', transfer_out: 'Transferencia saliente',
    card_payment: 'Pago con tarjeta', refund: 'Reembolso', fee_type: 'Comisión', cashback: 'Cashback',
    card_activation: 'Activación de tarjeta', card_transfer: 'Transferencia entre tarjetas', bank_transfer: 'Transferencia bancaria',
    bank_transfer_incoming: 'Transf. bancaria entrante', crypto_withdrawal: 'Retiro cripto', crypto_send: 'Envío cripto',
    crypto_deposit: 'Depósito cripto', crypto_to_card: 'Cripto → Tarjeta', crypto_to_iban: 'Cripto → IBAN',
    crypto_to_crypto: 'Cripto → Cripto', bank_to_crypto: 'Banco → Cripto', iban_to_iban: 'IBAN → IBAN',
    internal_transfer: 'Transferencia interna', payment: 'Pago',
    confidential: 'Documento confidencial · Solo para uso personal',
  },
};

function t(lang: Lang, key: string): string {
  return i18n[lang]?.[key] || i18n['en'][key] || key;
}

function getStatusLabel(status: string, lang: Lang): string {
  return t(lang, status) || status;
}

function getTypeLabel(type: string, lang: Lang): string {
  return t(lang, type) || type;
}

function getLocale(lang: Lang): string {
  const localeMap: Record<Lang, string> = { ru: 'ru-RU', en: 'en-US', de: 'de-DE', tr: 'tr-TR', zh: 'zh-CN', ar: 'ar-AE', es: 'es-ES' };
  return localeMap[lang] || 'en-US';
}

interface AssetBalance {
  label: string;
  amount: string;
  currency: string;
}

// ─── PDF Generation ───
function buildPDF(
  filtered: any[],
  periodLabel: string,
  userName: string,
  generatedDate: string,
  totalIn: number,
  totalOut: number,
  assetBalances: AssetBalance[],
  lang: Lang,
): ArrayBuffer {
  const locale = getLocale(lang);
  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 12;
  let y = 0;

  // ── Colors
  const blue: [number, number, number] = [0, 122, 255];
  const dark: [number, number, number] = [30, 41, 59];
  const gray: [number, number, number] = [100, 116, 139];
  const green: [number, number, number] = [16, 185, 129];
  const red: [number, number, number] = [239, 68, 68];
  const white: [number, number, number] = [255, 255, 255];
  const lightBg: [number, number, number] = [241, 245, 249];

  // ── Header background
  doc.setFillColor(10, 10, 10);
  doc.rect(0, 0, pageWidth, 52, 'F');

  // Blue glow circle
  doc.setFillColor(0, 122, 255);
  doc.setGState(new (doc as any).GState({ opacity: 0.15 }));
  doc.circle(pageWidth - 40, 10, 50, 'F');
  doc.setGState(new (doc as any).GState({ opacity: 1 }));

  // Brand
  doc.setTextColor(...white);
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('uEasyCard', margin, 14);

  // Report title
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(200, 200, 200);
  doc.text(t(lang, 'reportTitle'), margin, 22);

  // Period
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...white);
  doc.text(periodLabel, margin, 32);

  // Balance chips
  if (assetBalances.length > 0) {
    let chipX = margin;
    doc.setFontSize(7);
    for (const b of assetBalances) {
      const text = `${b.label}: ${b.amount} ${b.currency}`;
      const tw = doc.getTextWidth(text) + 6;
      doc.setFillColor(255, 255, 255);
      doc.setGState(new (doc as any).GState({ opacity: 0.12 }));
      doc.roundedRect(chipX, 36, tw, 6, 1.5, 1.5, 'F');
      doc.setGState(new (doc as any).GState({ opacity: 1 }));
      doc.setTextColor(...white);
      doc.setFont('helvetica', 'normal');
      doc.text(text, chipX + 3, 40);
      chipX += tw + 3;
    }
  }

  // Right side: user & date
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...white);
  if (userName) {
    doc.text(userName, pageWidth - margin, 14, { align: 'right' });
  }
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(180, 180, 180);
  doc.text(`${t(lang, 'generatedOn')}: ${generatedDate}`, pageWidth - margin, 20, { align: 'right' });
  doc.text(t(lang, 'autoGenerated'), pageWidth - margin, 25, { align: 'right' });
  doc.text('uEasyCard Financial Services', pageWidth - margin, 30, { align: 'right' });

  y = 52;

  // ── Summary cards
  const summaryY = y + 4;
  const cardW = (pageWidth - margin * 2 - 12) / 4;
  const cardH = 18;

  const summaryItems = [
    { label: t(lang, 'totalOps'), value: String(filtered.length), color: dark },
    { label: t(lang, 'income'), value: `+${totalIn.toLocaleString(locale, { minimumFractionDigits: 2 })} AED`, color: green },
    { label: t(lang, 'expense'), value: `-${totalOut.toLocaleString(locale, { minimumFractionDigits: 2 })} AED`, color: red },
    { label: t(lang, 'balance'), value: `${(totalIn - totalOut).toLocaleString(locale, { minimumFractionDigits: 2 })} AED`, color: blue },
  ];

  summaryItems.forEach((item, idx) => {
    const x = margin + idx * (cardW + 4);
    doc.setFillColor(...white);
    doc.setDrawColor(226, 232, 240);
    doc.roundedRect(x, summaryY, cardW, cardH, 2, 2, 'FD');

    doc.setFontSize(7);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...gray);
    doc.text(item.label.toUpperCase(), x + 5, summaryY + 6);

    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...(item.color as [number, number, number]));
    doc.text(item.value, x + 5, summaryY + 14);
  });

  y = summaryY + cardH + 8;

  // ── Detail title
  doc.setFillColor(...blue);
  doc.roundedRect(margin, y, 1.5, 6, 0.5, 0.5, 'F');
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...dark);
  doc.text(t(lang, 'detailTitle'), margin + 5, y + 5);
  y += 10;

  // ── Transaction table
  const tableHeaders = [
    t(lang, 'num'), t(lang, 'date'), t(lang, 'type'), t(lang, 'description'),
    t(lang, 'amount'), t(lang, 'status'), t(lang, 'sender'), t(lang, 'receiver'), t(lang, 'fee'),
  ];

  const tableRows = filtered.map((tx: any, idx: number) => {
    const date = tx.created_at ? `${formatDate(tx.created_at)} ${formatTime(tx.created_at)}` : '';
    const type = getTypeLabel(tx.type, lang);

    let description = '';
    if (tx.display?.title) {
      description = tx.display.title;
      if (tx.display.subtitle) description += ` (${tx.display.subtitle})`;
    } else if (tx.merchant_name) {
      description = tx.merchant_name;
    } else if (tx.description) {
      description = tx.description;
    }

    let amount = '';
    let sign = '';
    if (tx.display?.primary_amount) {
      const pa = tx.display.primary_amount;
      sign = pa.sign || '';
      amount = `${sign}${pa.amount}`;
    } else if (tx.amount !== undefined) {
      amount = String(tx.amount);
      sign = parseFloat(tx.amount) >= 0 ? '+' : '-';
    }
    const currency = tx.display?.primary_amount?.currency || tx.currency || 'AED';
    amount = `${amount} ${currency}`;

    const status = getStatusLabel(tx.status, lang);

    // Sender
    const senderName = tx.sender_name || tx.metadata?.sender_name || '—';
    const senderDetails: string[] = [];
    if (tx.sender_card_mask) senderDetails.push(`•••• ${tx.sender_card_mask.slice(-4)}`);
    const sIban = tx.metadata?.sender_iban_mask || tx.metadata?.sender_iban || tx.metadata?.from_iban;
    if (sIban) { const s = String(sIban); senderDetails.push(s.length > 8 ? `${s.slice(0, 4)}••${s.slice(-4)}` : s); }
    const sAddr = tx.metadata?.from_address || tx.metadata?.from_wallet_address || tx.metadata?.crypto_address;
    if (sAddr) { const a = String(sAddr); senderDetails.push(`${a.slice(0, 6)}••${a.slice(-4)}`); }
    if (tx.metadata?.from_card_number) { const c = String(tx.metadata.from_card_number); senderDetails.push(`•••• ${c.slice(-4)}`); }
    if (senderDetails.length === 0 && tx.movements?.[0]) {
      const m = tx.movements[0];
      if (m.card_mask) senderDetails.push(`•••• ${m.card_mask.slice(-4)}`);
      else if (m.iban) { const i = String(m.iban); senderDetails.push(`${i.slice(0, 4)}••${i.slice(-4)}`); }
    }
    const senderStr = senderDetails.length > 0 ? `${senderName}\n${senderDetails.join(' · ')}` : senderName;

    // Receiver
    const receiverName = tx.receiver_name || tx.metadata?.beneficiary_name || tx.metadata?.receiver_name || '—';
    const receiverDetails: string[] = [];
    if (tx.receiver_card_mask) receiverDetails.push(`•••• ${tx.receiver_card_mask.slice(-4)}`);
    const rIban = tx.metadata?.receiver_iban_mask || tx.metadata?.beneficiary_iban || tx.metadata?.receiver_iban || tx.metadata?.to_iban;
    if (rIban) { const s = String(rIban); receiverDetails.push(s.length > 8 ? `${s.slice(0, 4)}••${s.slice(-4)}` : s); }
    const rAddr = tx.metadata?.to_address || tx.metadata?.to_wallet_address || tx.metadata?.receiver_crypto_address;
    if (rAddr) { const a = String(rAddr); receiverDetails.push(`${a.slice(0, 6)}••${a.slice(-4)}`); }
    const rCard = tx.metadata?.receiver_card_number || tx.metadata?.to_card_number || tx.metadata?.card_number || tx.metadata?.to_card_mask;
    if (rCard) { const c = String(rCard); receiverDetails.push(`•••• ${c.slice(-4)}`); }
    if (receiverDetails.length === 0 && tx.movements?.length > 1) {
      const m = tx.movements[1];
      if (m?.card_mask) receiverDetails.push(`•••• ${m.card_mask.slice(-4)}`);
      else if (m?.iban) { const i = String(m.iban); receiverDetails.push(`${i.slice(0, 4)}••${i.slice(-4)}`); }
    }
    if (receiverDetails.length === 0 && tx.display?.subtitle) {
      const cardMatch = String(tx.display.subtitle).match(/(\d{4})\s*$/);
      if (cardMatch) receiverDetails.push(`•••• ${cardMatch[1]}`);
    }
    const receiverStr = receiverDetails.length > 0 ? `${receiverName}\n${receiverDetails.join(' · ')}` : receiverName;

    const fee = tx.fee !== undefined && tx.fee !== null ? `${tx.fee} ${currency}` : '—';

    return [String(idx + 1), date, type, description || '—', amount, status, senderStr, receiverStr, fee];
  });

  (doc as any).autoTable({
    head: [tableHeaders],
    body: tableRows,
    startY: y,
    margin: { left: margin, right: margin },
    styles: {
      fontSize: 7,
      cellPadding: 2.5,
      lineColor: [241, 245, 249],
      lineWidth: 0.3,
      textColor: dark,
      font: 'helvetica',
    },
    headStyles: {
      fillColor: lightBg,
      textColor: gray,
      fontStyle: 'bold',
      fontSize: 6.5,
      halign: 'left',
    },
    alternateRowStyles: {
      fillColor: [250, 251, 252],
    },
    columnStyles: {
      0: { halign: 'center', cellWidth: 8 },   // #
      1: { cellWidth: 28 },                      // Date
      2: { cellWidth: 26 },                      // Type
      3: { cellWidth: 'auto' },                  // Description
      4: { halign: 'right', cellWidth: 28, fontStyle: 'bold' }, // Amount
      5: { cellWidth: 20 },                      // Status
      6: { cellWidth: 32, fontSize: 6 },         // Sender
      7: { cellWidth: 32, fontSize: 6 },         // Receiver
      8: { cellWidth: 20, halign: 'right' },     // Fee
    },
    didParseCell: (data: any) => {
      // Color amount column
      if (data.section === 'body' && data.column.index === 4) {
        const val = String(data.cell.raw || '');
        if (val.startsWith('+')) data.cell.styles.textColor = green;
        else if (val.startsWith('-')) data.cell.styles.textColor = red;
      }
    },
    didDrawPage: () => {
      // Footer on each page
      const pg = doc.internal.getCurrentPageInfo().pageNumber;
      doc.setFontSize(7);
      doc.setTextColor(...gray);
      doc.text(`uEasyCard © ${new Date().getFullYear()}`, margin, pageHeight - 6);
      doc.text(t(lang, 'confidential'), pageWidth / 2, pageHeight - 6, { align: 'center' });
      doc.text(`${pg}`, pageWidth - margin, pageHeight - 6, { align: 'right' });
    },
  });

  return doc.output('arraybuffer');
}

// ─── i18n for delivery messages ───
const deliveryI18n: Record<Lang, Record<string, string>> = {
  ru: { card: 'Карты', iban: 'Счета IBAN', crypto: 'Крипто кошельки' },
  en: { card: 'Cards', iban: 'IBAN Accounts', crypto: 'Crypto Wallets' },
  de: { card: 'Karten', iban: 'IBAN-Konten', crypto: 'Krypto-Wallets' },
  tr: { card: 'Kartlar', iban: 'IBAN Hesapları', crypto: 'Kripto Cüzdanları' },
  zh: { card: '卡', iban: 'IBAN 账户', crypto: '加密钱包' },
  ar: { card: 'بطاقات', iban: 'حسابات IBAN', crypto: 'محافظ كريبتو' },
  es: { card: 'Tarjetas', iban: 'Cuentas IBAN', crypto: 'Billeteras Cripto' },
};

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const {
      backend_token, start_date, end_date, user_name, asset_filter,
      lang: rawLang, delivery_channels, also_download, asset_labels: rawAssetLabels,
    } = await req.json();
    const lang: Lang = (['ru','en','de','tr','zh','ar','es'].includes(rawLang) ? rawLang : 'en') as Lang;
    const locale = getLocale(lang);
    const filterAssets = Array.isArray(asset_filter) && asset_filter.length > 0 ? asset_filter : null;

    if (!backend_token) {
      return new Response(
        JSON.stringify({ error: t(lang, 'notAuthorized') }),
        { status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const BACKEND_BASE = "https://ueasycard.com/api/v1";
    const headers = {
      "Content-Type": "application/json",
      "Authorization": `Token ${backend_token}`,
    };

    // Fetch transactions and balances in parallel
    const [response, walletRes, bankRes, cryptoRes] = await Promise.all([
      fetch(`${BACKEND_BASE}/transactions/all/`, { method: "GET", headers }),
      fetch(`${BACKEND_BASE}/cards/wallet/summary/`, { method: "GET", headers }).catch(() => null),
      fetch(`${BACKEND_BASE}/transactions/bank-accounts/`, { method: "GET", headers }).catch(() => null),
      fetch(`${BACKEND_BASE}/transactions/crypto-wallets/`, { method: "GET", headers }).catch(() => null),
    ]);

    if (!response.ok) {
      console.error("Transactions API error:", response.status);
      return new Response(
        JSON.stringify({ error: t(lang, 'fetchError') }),
        { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Parse balances
    const assetBalances: AssetBalance[] = [];
    const includeCards = !filterAssets || filterAssets.includes('card');
    const includeIban = !filterAssets || filterAssets.includes('iban');
    const includeCrypto = !filterAssets || filterAssets.includes('crypto');

    try {
      if (walletRes?.ok) {
        const wallet = await walletRes.json();
        if (includeCards && wallet.cards && Array.isArray(wallet.cards)) {
          for (const card of wallet.cards) {
            const bal = parseFloat(String(card.balance || 0));
            if (bal > 0 || card.card_mask) {
              const rawType = card.card_type || card.type || t(lang, 'card');
              const cardType = rawType.charAt(0).toUpperCase() + rawType.slice(1).toLowerCase();
              const mask = card.card_mask ? `•••• ${String(card.card_mask).slice(-4)}` : '';
              assetBalances.push({ label: `${cardType} ${mask}`.trim(), amount: bal.toLocaleString(locale, { minimumFractionDigits: 2 }), currency: 'AED' });
            }
          }
        }
        if (includeCrypto && wallet.usdt_balance !== undefined) {
          const usdtBal = parseFloat(String(wallet.usdt_balance || 0));
          assetBalances.push({ label: `${t(lang, 'wallet')} USDT`, amount: usdtBal.toLocaleString(locale, { minimumFractionDigits: 2 }), currency: 'USDT' });
        }
      }
    } catch (e) { console.error("Wallet parse error:", e); }

    try {
      if (includeIban && bankRes?.ok) {
        const bankData = await bankRes.json();
        const accounts = Array.isArray(bankData) ? bankData : (bankData?.results || []);
        for (const acc of accounts) {
          const bal = parseFloat(String(acc.balance || 0));
          const iban = acc.iban ? `${String(acc.iban).slice(0, 4)}••••${String(acc.iban).slice(-4)}` : 'IBAN';
          assetBalances.push({ label: `${t(lang, 'account')} ${iban}`, amount: bal.toLocaleString(locale, { minimumFractionDigits: 2 }), currency: acc.currency || 'AED' });
        }
      }
    } catch (e) { console.error("Bank parse error:", e); }

    try {
      if (includeCrypto && cryptoRes?.ok) {
        const cryptoData = await cryptoRes.json();
        const wallets = Array.isArray(cryptoData) ? cryptoData : (cryptoData?.results || []);
        for (const w of wallets) {
          const bal = parseFloat(String(w.balance || 0));
          const token = w.token || 'USDT';
          if (token === 'USDT' && assetBalances.some(a => a.label.includes('USDT'))) continue;
          assetBalances.push({ label: `${t(lang, 'wallet')} ${token}`, amount: bal.toLocaleString(locale, { minimumFractionDigits: 2 }), currency: token });
        }
      }
    } catch (e) { console.error("Crypto parse error:", e); }

    const rawData = await response.json();
    const allTransactions = Array.isArray(rawData) ? rawData : (rawData?.results || rawData?.data || []);

    let filtered = allTransactions;
    if (start_date || end_date) {
      const startMs = start_date ? new Date(start_date).getTime() : 0;
      const endMs = end_date ? new Date(end_date + "T23:59:59").getTime() : Date.now();
      filtered = allTransactions.filter((tx: any) => {
        const txDate = new Date(tx.created_at).getTime();
        return txDate >= startMs && txDate <= endMs;
      });
    }

    // Filter by asset type
    if (filterAssets) {
      filtered = filtered.filter((tx: any) => {
        const txType = String(tx.type || '').toLowerCase();
        const currency = String(tx.currency || tx.display?.primary_amount?.currency || '').toUpperCase();
        if (includeCards) {
          if (txType === 'card_payment' || txType === 'card_activation' || txType === 'card_transfer' || txType === 'payment') return true;
          if (tx.card_id) return true;
          if (txType === 'top_up' || txType === 'topup') return true;
        }
        if (includeIban) {
          if (txType.includes('bank') || txType.includes('iban') || txType === 'withdrawal') return true;
          if (txType === 'transfer_in' || txType === 'transfer_out' || txType === 'internal_transfer') return true;
        }
        if (includeCrypto) {
          if (txType.includes('crypto')) return true;
          if (currency === 'USDT' || currency === 'BTC' || currency === 'ETH') return true;
        }
        return false;
      });
    }

    const totalIn = filtered
      .filter((tx: any) => {
        const sign = tx.display?.primary_amount?.sign;
        const amt = parseFloat(String(tx.display?.primary_amount?.amount || tx.amount || 0).replace(/,/g, ''));
        return sign === '+' || (!sign && amt > 0);
      })
      .reduce((sum: number, tx: any) => {
        const amt = parseFloat(String(tx.display?.primary_amount?.amount || tx.amount || 0).replace(/,/g, ''));
        return sum + (isNaN(amt) ? 0 : Math.abs(amt));
      }, 0);

    const totalOut = filtered
      .filter((tx: any) => {
        const sign = tx.display?.primary_amount?.sign;
        const amt = parseFloat(String(tx.display?.primary_amount?.amount || tx.amount || 0).replace(/,/g, ''));
        return sign === '-' || (!sign && amt < 0);
      })
      .reduce((sum: number, tx: any) => {
        const amt = parseFloat(String(tx.display?.primary_amount?.amount || tx.amount || 0).replace(/,/g, ''));
        return sum + (isNaN(amt) ? 0 : Math.abs(amt));
      }, 0);

    const periodLabel = start_date && end_date
      ? `${formatDate(start_date)} — ${formatDate(end_date)}`
      : start_date
        ? `${t(lang, 'from')} ${formatDate(start_date)}`
        : end_date
          ? `${t(lang, 'to')} ${formatDate(end_date)}`
          : t(lang, 'allTx');

    const generatedDate = formatDate(new Date().toISOString());

    // Generate PDF
    const pdfBuffer = buildPDF(filtered, periodLabel, user_name || '', generatedDate, totalIn, totalOut, assetBalances, lang);
    const pdfBytes = new Uint8Array(pdfBuffer);

    const fileDate = new Date().toISOString().slice(0, 10).replace(/-/g, '');
    const fileName = `uEasyCard_Report_${fileDate}.pdf`;

    // ─── Delivery channels logic ───
    const channelsToSend = Array.isArray(delivery_channels) ? delivery_channels.filter((c: string) => c !== 'download') : [];

    if (channelsToSend.length > 0) {
      const di = deliveryI18n[lang] || deliveryI18n['en'];
      const assetLabels: string[] = [];
      if (filterAssets) {
        if (filterAssets.includes('card')) assetLabels.push(di.card);
        if (filterAssets.includes('iban')) assetLabels.push(di.iban);
        if (filterAssets.includes('crypto')) assetLabels.push(di.crypto);
      }

      // Convert PDF to base64 for backend delivery
      const pdfBase64 = btoa(String.fromCharCode(...pdfBytes));

      try {
        const sendRes = await fetch(`${BACKEND_BASE}/accounts/statement/send/`, {
          method: 'POST',
          headers,
          body: JSON.stringify({
            pdf_base64: pdfBase64,
            file_name: fileName,
            channels: channelsToSend,
            period_label: periodLabel,
            asset_labels: assetLabels,
            lang,
          }),
        });
        const sendData = await sendRes.json();
        console.log("Statement delivery results:", JSON.stringify(sendData));

        if (also_download) {
          return new Response(pdfBytes, {
            headers: {
              ...corsHeaders,
              "Content-Type": "application/pdf",
              "Content-Disposition": `attachment; filename="${fileName}"`,
              "X-Delivery-Results": JSON.stringify(sendData.results || {}),
            },
          });
        }

        return new Response(
          JSON.stringify({ ok: true, delivery: sendData.results || {} }),
          { status: 200, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      } catch (sendErr) {
        console.error("Statement delivery error:", sendErr);
        if (also_download) {
          return new Response(pdfBytes, {
            headers: {
              ...corsHeaders,
              "Content-Type": "application/pdf",
              "Content-Disposition": `attachment; filename="${fileName}"`,
            },
          });
        }
        return new Response(
          JSON.stringify({ ok: false, error: "Delivery failed" }),
          { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }
    }

    // No delivery channels — just return PDF file
    return new Response(pdfBytes, {
      headers: {
        ...corsHeaders,
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="${fileName}"`,
      },
    });
  } catch (error) {
    console.error("Report generation error:", error);
    return new Response(
      JSON.stringify({ error: "Report generation error" }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
